### ISSUE TITLE
ChannelFull exception when using django-rest-framework Response

### ISSUE THREAD

**Issue by jarrizabalaga** [andrewgodwin/asgiref#2]
We want to return a 5MB file using django-rest-framework Response method:

```
from rest_framework.response import Response
...
data=open(_filename_, "rb").read()
return Response(data=ujson.loads(data), status=200)
```

But we're getting ChannelFull exception.

We tried to increase the capacity parameter and it worked. I also go back to version 0.11.2 of asgiref and it also worked (ChannelFull exception and parameter were not still developed).
Changing the chunk_size also makes the things work.

This is the traceback we get in the exception:
2016-07-21 17:16:57,101 - ERROR - worker - Error processing message with consumer channels.handler.ViewConsumer:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\channels\worker.py", line 78, in run
    consumer(message, **kwargs)
  File "C:\Anaconda3\lib\site-packages\channels\handler.py", line 329, in __call__
    message.reply_channel.send(reply_message)
  File "C:\Anaconda3\lib\site-packages\channels\channel.py", line 38, in send
    self.channel_layer.send(self.name, content)
  File "C:\Anaconda3\lib\site-packages\asgiref\inmemory.py", line 50, in send
    raise self.ChannelFull(channel)
asgiref.inmemory.ChannelLayer.ChannelFull: http.response!gMEQvWNb

**Comment by andrewgodwin** [comment]
Continuing from Twitter - ChannelFull is expected in this situation, as the client is not consuming the data as fast as you're generating it, so things should be chunked up. Django is meant to do this automatically, but obviously isn't in this situation.

Can I get the full traceback of the exception so I can work out what response path it's going through?

**Comment by jarrizabalaga** [comment]
I updated the first comment with the traceback I got.

**Comment by andrewgodwin** [comment]
OK, in my copy of that code it catches ChannelFull the exact line after the one your traceback is raising from - are you sure you have the latest version of the `channels` package?

**Comment by jarrizabalaga** [comment]
You are right!! I updated `asgiref` but not `channels`. After updating it to the last version, everything is working again.

Thank you very much and apologize to bother you.

**Comment by lingliqianxun** [comment]
I also have the same problem，my version is websocket-client (0.40.0).should be chunked up?
