### ISSUE TITLE
Slashes excluded from group names

### ISSUE THREAD

**Issue by yourcelf** [andrewgodwin/asgiref#3]
https://github.com/andrewgodwin/asgiref/commit/c2d93f5e63aa64c30f01755dedc5f7bbddb4482a added validators to limit the characters allowed in group names.  In our application, it's very natural to use the `message.content['path']` (i.e. the URL) as a group name.  This was working great until we upgraded and found that `/` is no longer a valid group name character.

Is there a good reason to exclude `/` from group names?  If so, we'll add a translation to some other character.  But if not, we'd love to see slashes added to the character class in `group_name_regex`.

**Comment by andrewgodwin** [comment]
It was in particular in the case of groups being stored on some filesystem-backed store, where `/` is nearly always invalid. I'm unlikely to budge on this; can you find a way to translate the path into a group name programatically (e.g. with replacement)?

**Comment by yourcelf** [comment]
Yup, makes sense, thanks.
